version: latest

services:
  db_social_nest:
    image: postgres:alpine
    container_name: db_social_nest
    restart: always
    ports:
      - 5435:5432
    env_file:
      - ./db/.env
    volumes:
      - db_social_nest_volume:/docker-entrypoint-initdb.d
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  backend_social_nest:
    build: ./backend 
    container_name: backend_social_nest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 3100:3100
      - 5557:5555
    volumes:
      - ./backend:/usr/social_nest
    links:
      - db_social_nest
    depends_on:
      - db_social_nest
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
  db_social_nest_volume:
  